import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from 'next/dynamic';
import React, { useEffect, useState } from 'react'
import { importModule } from "@/importModule";
const inter = Inter({ subsets: ["latin"] });

const Button = dynamic(() => import('mfe1/button'))

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>Home Page</div>
        {!!Button && <Button>Rendered in home</Button>}
      </main>
    </>
  );
}
